language: java
sudo: true
dist: trusty
before_install:
  - chmod +x mvnw
git:
  depth: 1
cache:
  directories:
    - $HOME/.m2
install: true
env:
  global:
matrix:
  include:
    - os: linux
      jdk: openjdk12
script: 
  - ./mvnw clean package -Dmaven.javadoc.skip=false
  - ./mvnw sonar:sonar -Dsonar.projectKey=cyanpotion_multi_language -Dsonar.organization=cyanpotion -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a279ba08f021523fa7fd0c2d8a2ebff8afde8501